language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: vYdbRLwX/Ki61ERSRJqriL0NM1IgKWVfMhlPfGOHniaLFAzOEvilqXStTBNcbc4oif3McPdgqbdXUiP2nwY8buHmLdNcNoVn5ubyf1IXXvu5BltVs978/xxyV7EW6TBvFlCbdUFBhtMf8F8nx8tkOh2z9T2WN6X6fJbZg+8dJ0ALcDF5XxeK2+a4bJEuEeWJQ4OLiHaocdlIXQeBGL2pTL2QQrwfvnIIfeiavRsTTM8hfnuBKLLAHhXF0UxuaxYxe5W8ZsKONzAuWLqVBvGTnaRhwJaQ+b/GzrlNliEjU9Vt4yFbPCCf3te2jdEnK+/vzeY8OBriBBNYI2dG9EIjoqwczT+FSXAAISfmUmZa106fmfFrfEwfajUAcHhtp10E3jc5OQBPdCA5J+LZ9eHorc0xvKgwNe1y7lGGz6lrxxcGiYhfL5iXv+48sskun+bnSXy2ZkIoGkecyW03vB8mXqZDI7Z7pBo6hVOBOhOBetFnORC/g/ymaQm/bJCDoIF2dOGJd+bYtYVoKx04cNurPgMua78kVD3pKnB22p38WhHspkTFHmOLm8AUdoQJJBKRPE2N8EU1RQYofSOZhuSj2UAjAM0rm9u5Z++Q4bnZvbi+53j6gXMlX0oiRes6MDSa0xlr5IgtWOZF4TBOUtcNU8UZLP6F3iH1luP4XSYWxaE=
  app: eldar-123
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
